name: Deploy gh-pages

on:
  push:
    branches:
      - source

jobs:
  markdown_lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: DavidAnson/markdownlint-cli2-action@v18
        with:
          config: '.markdownlint.yaml'
          globs: '**/*.md'

  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v1
        with:
          node-version: '19.3.0'

      - name: Setup just
        uses: extractions/setup-just@v1

      - name: Install dependencies
        run: just prepare-deploy

      - name: Build
        run: |
          just clean
          just build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
          publish_branch: main
          commit_message: ${{ github.event.head_commit.message }}
